chore: validate the yaml file
Signed-off-by: Andrew Brandt <andrew.brandt@hashgraph.com>

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -22,6 +22,14 @@ runs:
         chmod +x /usr/local/bin/yq
       shell: bash
 
+    - name: Validate YAML file
+      run: |
+        if [[ ! -f "${{ inputs.yaml_file }}" ]]; then
+          echo "Error: YAML file not found!"
+          exit 1
+        fi
+      shell: bash
+
     - name: Read YAML and update repository property
       env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
